### ISSUE TITLE
解压出错

### ISSUE THREAD

**Issue by wangdsh** [ownthink/KnowledgeGraphData#11]
好不容易下载下来，密码验证正确，但文件似乎已损坏，无法解压。试了2次都是这样。有解决方法吗？

**Comment by ownthink** [comment]
方法是有，就是用我们自己的服务器提供下载，但是服务器费用有点高


你可以找找云盘快速下载方式的。

郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangdsh"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午5:41
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/KnowledgeGraphData] 解压出错 (#11)




好不容易下载下来，密码验证正确，但文件似乎已损坏，无法解压。试了2次都是这样。有解决方法吗？

**Comment by wangdsh** [comment]
同学用会员下载的，下载10MB每秒，也无法解压。方便重新上传一下吗

**Comment by ownthink** [comment]
你加我qq：15876050，我晚上给你远程协助



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangdsh"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午5:51
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/KnowledgeGraphData] 解压出错 (#11)




同学用会员下载的，下载10MB每秒，也无法解压。方便重新上传一下吗

**Comment by wangdsh** [comment]
我发送了好友请求～

**Comment by hggq** [comment]
用命令行 解压可以，mac os 直接解压，也报错，直接用unzip解压

**Comment by wangdsh** [comment]
qq号少了一位==，用unzip解压好像可以：
$ unzip ownthink_v2.zip
Archive:  ownthink_v2.zip

??ѹ???룺https://www.ownthink.com/
[ownthink_v2.zip] ownthink_v2.csv password: 
  inflating: ownthink_v2.csv         
  error:  invalid compressed data to inflate

共33630842行，感觉没有解压完~

**Comment by ownthink** [comment]
@wangdsh 不好意思，键盘不好使，QQ号少了一位，已经补上

**Comment by wangdsh** [comment]
已发送验证消息～

**Comment by houking-can** [comment]
> qq号少了一位==，用unzip解压好像可以：
> $ unzip ownthink_v2.zip
> Archive: ownthink_v2.zip
> 
> ??ѹ???룺https://www.ownthink.com/
> [ownthink_v2.zip] ownthink_v2.csv password:
> inflating: ownthink_v2.csv
> error: invalid compressed data to inflate
> 
> 共33630842行，感觉没有解压完~

同学你解压成功了吗？我也遇到同样的错误
