### ISSUE TITLE
好多行错乱，不匹配的单双引号

### ISSUE THREAD

**Issue by graphnj** [ownthink/KnowledgeGraphData#19]
好多将双引号间的内容分到多行去了， 用的什么换行符？ 怎么修复才能用

egrep -v ",.*?,.*$" ownthink_v2.csv
可以这样看一下

欧洲联盟杯冠军（1989）
意大利超级杯（1990，2014）
意大利杯（1962，1976，1987，2012，2014）"
1986年世界杯第四名"
33次苏格兰杯冠军
27次苏格兰联赛杯冠军
1次欧洲优胜者杯冠军
1次苏格兰丙级联赛冠军"
Aiolos"
3次欧洲杯冠军
1次奥运会冠军
1次联合会杯冠军"
Shimura Shinpachi（罗马音）"
学院救援团（客串）
齐木楠雄的灾难第二季（客串）"
Kagura（罗马音）"
美韩军伤亡2.5万

"
Hijikata Toushirou（罗马音）"
おきた そうご（平假名）
Okita Sougo（罗马音）"
Katsura Kotarou"

**Comment by ownthink** [comment]
用csv读取方式。。。。你直接用逗号分隔肯定不行啊。

郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"graphnj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 中午1:27
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/KnowledgeGraphData] 好多行错乱，不匹配的单双引号 (#19)





 
好多将双引号间的内容分到多行去了， 用的什么换行符？ 怎么修复才能用
 
egrep -v ",.?,.$" ownthink_v2.csv
 可以这样看一下
 
欧洲联盟杯冠军（1989）
 意大利超级杯（1990，2014）
 意大利杯（1962，1976，1987，2012，2014）"
 1986年世界杯第四名"
 33次苏格兰杯冠军
 27次苏格兰联赛杯冠军
 1次欧洲优胜者杯冠军
 1次苏格兰丙级联赛冠军"
 Aiolos"
 3次欧洲杯冠军
 1次奥运会冠军
 1次联合会杯冠军"
 Shimura Shinpachi（罗马音）"
 学院救援团（客串）
 齐木楠雄的灾难第二季（客串）"
 Kagura（罗马音）"
 美韩军伤亡2.5万
 
"
 Hijikata Toushirou（罗马音）"
 おきた そうご（平假名）
 Okita Sougo（罗马音）"
 Katsura Kotarou"

**Comment by graphnj** [comment]
是csv啊， neo4j的load csv失败， pandas的read_csv失败
实际内容是双引号中含多条记录时，用换行符分割了吧

文件是直接centos7下解压的，看上去是windows的\r\n回车换行，

**Comment by ownthink** [comment]
不是的，这个是正常的csv格式，需要自己处理才能给neo4j用，你不要用pandas的，直接用import csv

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"graphnj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 中午12:28
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/KnowledgeGraphData] 好多行错乱，不匹配的单双引号 (#19)





 
是csv啊， neo4j的load csv失败， pandas的read_csv失败
 实际内容是双引号中含多条记录时，用换行符分割了吧
 
文件是直接centos7下解压的，看上去是windows的\r\n回车换行，

**Comment by Sakura-cheng** [comment]
意思是下载的整个ownthink_v2.csv不能直接导入neo4j吗？
麻烦问下，自己处理的思路是怎样的呢

**Comment by ownthink** [comment]
&nbsp;这个数据集是一个csv格式的三元组，可以自己转换成neo4j需要的格式，百度ownthink导入neo4j即可哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/KnowledgeGraphData"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 晚上7:54
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/KnowledgeGraphData] 好多行错乱，不匹配的单双引号 (#19)





 
意思是下载的整个ownthink_v2.csv不能直接导入neo4j吗？
 麻烦问下，自己处理的思路是怎样的呢
