### ISSUE TITLE
想請問關於引用論文

### ISSUE THREAD

**Issue by SachiaLanlus** [ownthink/KnowledgeGraphData#25]
您好
因為研究的關係 我需要在我的實驗中引述OwnThink Ontology
因為我在相關網頁都找不到引用的資訊
想請問如果我要引用的話
是否有提供相關的論文提供引用
或者是單位的名稱呢
感謝您

**Comment by ownthink** [comment]
&nbsp;只要著名来自于https://www.ownthink.com/即可



郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/KnowledgeGraphData"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 中午1:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ownthink/KnowledgeGraphData] 想請問關於引用論文 (#25)





 
您好
 因為研究的關係 我需要在我的實驗中引述OwnThink Ontology
 因為我在相關網頁都找不到引用的資訊
 想請問如果我要引用的話
 是否有提供相關的論文提供引用
 或者是單位的名稱呢
 感謝您

**Comment by SachiaLanlus** [comment]
好的 感謝您
