### ISSUE TITLE
问了两个问题，一个都没搜到

### ISSUE THREAD

**Issue by Gavin-J** [ownthink/KnowledgeGraphData#3]
马化腾的女儿，无匹配结果
马云的儿子， 无匹配结果

**Comment by ownthink** [comment]
没有这个实体知识，我也不知道马云的儿子是谁，马化腾的女儿

**Comment by sunff2050** [comment]
> 马化腾的女儿，无匹配结果
> 马云的儿子， 无匹配结果

怎么使用这个做的问答系统？能介绍下吗
